packages:
  - 'apps/*'
  - 'libs/*'
  - 'modules/*'
  - 'tools'
overrides:
  'eslint-config-prettier': '^10.0.1'
  'eslint': '^9.17.0'
  'vite': '^6.0.6'
  'typedoc': '^0.27.6'
  'tree-sitter': '^0.22.4'
  'react': '^19.1.0'
  'react-dom': '^19.1.0'
  'react-hook-form': '^7.56.1'
  'uri-js': '4.4.1'
  'whatwg-url': '^14.0.0'
  'webpack': '^5.97.1'
  'typescript': '^5.8.3'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - 'esbuild'
  - 'nx'
  - 'sharp'
  - 'unrs-resolver'
